
name: bikeshare_streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py38hca03da5_1001
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=2.122=openblas
  - blas-devel=3.9.0=22_osxarm64_openblas
  - brotli-python=1.0.9=py38h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.9.24=hca03da5_0
  - certifi=2024.8.30=py38hca03da5_0
  - debugpy=1.5.1=py38hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - geographiclib=2.0=py38hca03da5_0
  - geopy=2.4.1=py38hca03da5_0
  - idna=3.7=py38hca03da5_0
  - ipykernel=6.15.2=py38hca03da5_0
  - ipython=8.4.0=py38hca03da5_0
  - jedi=0.18.1=py38hca03da5_1
  - jupyter_client=7.3.5=py38hca03da5_0
  - jupyter_core=4.10.0=py38hca03da5_0
  - libblas=3.9.0=22_osxarm64_openblas
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.2=hc377ac9_4
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - liblapack=3.9.0=22_osxarm64_openblas
  - liblapacke=3.9.0=22_osxarm64_openblas
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libsodium=1.0.18=h1a28f6b_0
  - libzlib=1.2.12=h03a7124_3
  - llvm-openmp=18.1.6=hde57baf_0
  - matplotlib-inline=0.1.6=py38hca03da5_0
  - ncurses=6.3=h1a28f6b_3
  - nest-asyncio=1.5.5=py38hca03da5_0
  - openblas=0.3.27=openmp_h55c453e_0
  - openssl=3.0.15=h80987f9_0
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py38hca03da5_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py38h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38hca03da5_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.13=hd3575e6_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=23.2.0=py38hc377ac9_0
  - readline=8.1.2=h1a28f6b_1
  - setuptools=63.4.1=py38hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.2=py38h1a28f6b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - urllib3=2.2.1=py38hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1a28f6b_1
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.12=h5a0b063_3
  - folium
  - pip:
      - altair==5.3.0
      - attrs==23.2.0
      - blinker==1.8.2
      - branca==0.7.2
      - cachetools==5.3.3
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fiona==1.9.6
      - folium==0.16.0
      - fonttools==4.51.0
      - geopandas==0.13.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mouseinfo==0.1.3
      - numpy==1.24.4
      - pandas==2.0.3
      - pillow==9.2.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pyautogui==0.9.53
      - pydeck==0.9.1
      - pygetwindow==0.0.9
      - pygments==2.18.0
      - pymsgbox==1.0.9
      - pyobjc==8.5.1
      - pyobjc-core==8.5.1
      - pyobjc-framework-accessibility==8.5.1
      - pyobjc-framework-accounts==8.5.1
      - pyobjc-framework-addressbook==8.5.1
      - pyobjc-framework-adservices==8.5.1
      - pyobjc-framework-adsupport==8.5.1
      - pyobjc-framework-applescriptkit==8.5.1
      - pyobjc-framework-applescriptobjc==8.5.1
      - pyobjc-framework-applicationservices==8.5.1
      - pyobjc-framework-apptrackingtransparency==8.5.1
      - pyobjc-framework-audiovideobridging==8.5.1
      - pyobjc-framework-authenticationservices==8.5.1
      - pyobjc-framework-automaticassessmentconfiguration==8.5.1
      - pyobjc-framework-automator==8.5.1
      - pyobjc-framework-avfoundation==8.5.1
      - pyobjc-framework-avkit==8.5.1
      - pyobjc-framework-businesschat==8.5.1
      - pyobjc-framework-calendarstore==8.5.1
      - pyobjc-framework-callkit==8.5.1
      - pyobjc-framework-cfnetwork==8.5.1
      - pyobjc-framework-classkit==8.5.1
      - pyobjc-framework-cloudkit==8.5.1
      - pyobjc-framework-cocoa==8.5.1
      - pyobjc-framework-collaboration==8.5.1
      - pyobjc-framework-colorsync==8.5.1
      - pyobjc-framework-contacts==8.5.1
      - pyobjc-framework-contactsui==8.5.1
      - pyobjc-framework-coreaudio==8.5.1
      - pyobjc-framework-coreaudiokit==8.5.1
      - pyobjc-framework-corebluetooth==8.5.1
      - pyobjc-framework-coredata==8.5.1
      - pyobjc-framework-corehaptics==8.5.1
      - pyobjc-framework-corelocation==8.5.1
      - pyobjc-framework-coremedia==8.5.1
      - pyobjc-framework-coremediaio==8.5.1
      - pyobjc-framework-coremidi==8.5.1
      - pyobjc-framework-coreml==8.5.1
      - pyobjc-framework-coremotion==8.5.1
      - pyobjc-framework-coreservices==8.5.1
      - pyobjc-framework-corespotlight==8.5.1
      - pyobjc-framework-coretext==8.5.1
      - pyobjc-framework-corewlan==8.5.1
      - pyobjc-framework-cryptotokenkit==8.5.1
      - pyobjc-framework-datadetection==8.5.1
      - pyobjc-framework-devicecheck==8.5.1
      - pyobjc-framework-dictionaryservices==8.5.1
      - pyobjc-framework-discrecording==8.5.1
      - pyobjc-framework-discrecordingui==8.5.1
      - pyobjc-framework-diskarbitration==8.5.1
      - pyobjc-framework-dvdplayback==8.5.1
      - pyobjc-framework-eventkit==8.5.1
      - pyobjc-framework-exceptionhandling==8.5.1
      - pyobjc-framework-executionpolicy==8.5.1
      - pyobjc-framework-externalaccessory==8.5.1
      - pyobjc-framework-fileprovider==8.5.1
      - pyobjc-framework-fileproviderui==8.5.1
      - pyobjc-framework-findersync==8.5.1
      - pyobjc-framework-fsevents==8.5.1
      - pyobjc-framework-gamecenter==8.5.1
      - pyobjc-framework-gamecontroller==8.5.1
      - pyobjc-framework-gamekit==8.5.1
      - pyobjc-framework-gameplaykit==8.5.1
      - pyobjc-framework-imagecapturecore==8.5.1
      - pyobjc-framework-imserviceplugin==8.5.1
      - pyobjc-framework-inputmethodkit==8.5.1
      - pyobjc-framework-installerplugins==8.5.1
      - pyobjc-framework-instantmessage==8.5.1
      - pyobjc-framework-intents==8.5.1
      - pyobjc-framework-intentsui==8.5.1
      - pyobjc-framework-iosurface==8.5.1
      - pyobjc-framework-ituneslibrary==8.5.1
      - pyobjc-framework-kernelmanagement==8.5.1
      - pyobjc-framework-latentsemanticmapping==8.5.1
      - pyobjc-framework-launchservices==8.5.1
      - pyobjc-framework-libdispatch==8.5.1
      - pyobjc-framework-linkpresentation==8.5.1
      - pyobjc-framework-localauthentication==8.5.1
      - pyobjc-framework-localauthenticationembeddedui==8.5.1
      - pyobjc-framework-mailkit==8.5.1
      - pyobjc-framework-mapkit==8.5.1
      - pyobjc-framework-mediaaccessibility==8.5.1
      - pyobjc-framework-medialibrary==8.5.1
      - pyobjc-framework-mediaplayer==8.5.1
      - pyobjc-framework-mediatoolbox==8.5.1
      - pyobjc-framework-metal==8.5.1
      - pyobjc-framework-metalkit==8.5.1
      - pyobjc-framework-metalperformanceshaders==8.5.1
      - pyobjc-framework-metalperformanceshadersgraph==8.5.1
      - pyobjc-framework-metrickit==8.5.1
      - pyobjc-framework-mlcompute==8.5.1
      - pyobjc-framework-modelio==8.5.1
      - pyobjc-framework-multipeerconnectivity==8.5.1
      - pyobjc-framework-naturallanguage==8.5.1
      - pyobjc-framework-netfs==8.5.1
      - pyobjc-framework-network==8.5.1
      - pyobjc-framework-networkextension==8.5.1
      - pyobjc-framework-notificationcenter==8.5.1
      - pyobjc-framework-opendirectory==8.5.1
      - pyobjc-framework-osakit==8.5.1
      - pyobjc-framework-oslog==8.5.1
      - pyobjc-framework-passkit==8.5.1
      - pyobjc-framework-pencilkit==8.5.1
      - pyobjc-framework-photos==8.5.1
      - pyobjc-framework-photosui==8.5.1
      - pyobjc-framework-preferencepanes==8.5.1
      - pyobjc-framework-pushkit==8.5.1
      - pyobjc-framework-quartz==8.5.1
      - pyobjc-framework-quicklookthumbnailing==8.5.1
      - pyobjc-framework-replaykit==8.5.1
      - pyobjc-framework-safariservices==8.5.1
      - pyobjc-framework-scenekit==8.5.1
      - pyobjc-framework-screencapturekit==8.5.1
      - pyobjc-framework-screensaver==8.5.1
      - pyobjc-framework-screentime==8.5.1
      - pyobjc-framework-scriptingbridge==8.5.1
      - pyobjc-framework-searchkit==8.5.1
      - pyobjc-framework-security==8.5.1
      - pyobjc-framework-securityfoundation==8.5.1
      - pyobjc-framework-securityinterface==8.5.1
      - pyobjc-framework-servicemanagement==8.5.1
      - pyobjc-framework-shazamkit==8.5.1
      - pyobjc-framework-social==8.5.1
      - pyobjc-framework-soundanalysis==8.5.1
      - pyobjc-framework-speech==8.5.1
      - pyobjc-framework-spritekit==8.5.1
      - pyobjc-framework-storekit==8.5.1
      - pyobjc-framework-syncservices==8.5.1
      - pyobjc-framework-systemconfiguration==8.5.1
      - pyobjc-framework-systemextensions==8.5.1
      - pyobjc-framework-uniformtypeidentifiers==8.5.1
      - pyobjc-framework-usernotifications==8.5.1
      - pyobjc-framework-usernotificationsui==8.5.1
      - pyobjc-framework-videosubscriberaccount==8.5.1
      - pyobjc-framework-videotoolbox==8.5.1
      - pyobjc-framework-virtualization==8.5.1
      - pyobjc-framework-vision==8.5.1
      - pyobjc-framework-webkit==8.5.1
      - pyperclip==1.8.2
      - pyproj==3.5.0
      - pyrect==0.2.0
      - pyscreeze==0.1.28
      - pytweening==1.0.4
      - pytz==2024.1
      - referencing==0.35.1
      - requests==2.32.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rubicon-objc==0.4.2
      - shapely==2.0.4
      - smmap==5.0.1
      - streamlit==1.34.0
      - streamlit-folium==0.22.1
      - tenacity==8.3.0
      - toml==0.10.2
      - toolz==0.12.1
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - watchdog==4.0.0
      - xyzservices==2024.4.0
      - zipp==3.18.2
prefix: /opt/miniconda3/envs/bikeshare_streamlit

